instance creation
new

	^ self basicNew initializeWith: 'Afghanistan,Afghanistan,1
Albania,Albanie,3
Algeria,Algérie,4
American Samoa,Samoa Américaines,5
Andorra,Andorre,7
Angola,Angola,8
Anguilla,Anguilla,9
Antarctica,Antarctique,10
Antigua and Barbuda,Antigua-Et-Barbuda,11
Argentina,Argentine,12
Armenia,Arménie,13
Aruba,Aruba,14
Australia,Australie,17
Austria,Autriche,18
Azerbaijan,Azerbaïdjan,19
Bahamas,Bahamas,20
Bahrain,Bahreïn,21
Bangladesh,Bangladesh,23
Barbados,Barbade,24
Belarus,Bélarus,26
Belgium,Belgique,27
Belize,Belize,28
Benin,Bénin,29
Bermuda,Bermudes,30
Bhutan,Bhoutan,31
Bolivia; Plurinational State of,Bolivie; l''État Plurinational de,33
Bonaire; Sint Eustatius and Saba,Bonaire; Saint-Eustache et Saba,176
Bosnia and Herzegovina,Bosnie-Herzégovine,34
Botswana,Botswana,35
Bouvet Island,Bouvet; Île,36
Brazil,Brésil,37
British Indian Ocean Territory,Océan Indien; Territoire Britannique de l'',38
Brunei Darussalam,Brunei Darussalam,40
Bulgaria,Bulgarie,41
Burkina Faso,Burkina Faso,42
Burundi,Burundi,43
Cambodia,Cambodge,44
Cameroon,Cameroun,45
Canada,Canada,46
Cape Verde,Cap-Vert,47
Cayman Islands,Caïmans; Îles,48
Central African Republic,Centrafricaine; République,49
Chad,Tchad,50
Chile,Chili,51
China,Chine,53
Christmas Island,Christmas; Île,54
Cocos (Keeling) Islands,Cocos (Keeling); Îles,56
Colombia,Colombie,57
Comoros,Comores,58
Congo,Congo,59
Congo; the Democratic Republic of the,Congo; la République Démocratique du,68
Cook Islands,Cook; Îles,60
Costa Rica,Costa Rica,61
Croatia,Croatie,62
Cuba,Cuba,63
Curaçao,Curaçao,
Cyprus,Chypre,64
Czech Republic,Tchèque; République,65
Côte d''Ivoire,Côte d''Ivoire,66
Denmark,Danemark,69
Djibouti,Djibouti,70
Dominica,Dominique,71
Dominican Republic,Dominicaine; République,72
Ecuador,Équateur,73
Egypt,Égypte,40765
El Salvador,El Salvador,75
Equatorial Guinea,Guinée Équatoriale,76
Eritrea,Érythrée,77
Estonia,Estonie,78
Ethiopia,Éthiopie,79
Falkland Islands (Malvinas),Falkland; Îles (Malvinas),81
Faroe Islands,Féroé; Îles,82
Fiji,Fidji,83
Finland,Finlande,84
France,France,85
French Guiana,Guyane Française,86
French Polynesia,Polynésie Française,87
French Southern Territories,Terres Australes Françaises,88
Gabon,Gabon,89
Gambia,Gambie,90
Georgia,Géorgie,92
Germany,Allemagne,93
Ghana,Ghana,94
Gibraltar,Gibraltar,95
Greece,Grèce,97
Greenland,Groenland,98
Grenada,Grenade,99
Guadeloupe,Guadeloupe,100
Guam,Guam,101
Guatemala,Guatemala,103
Guernsey,Guernesey,104
Guinea,Guinée,106
Guinea-Bissau,Guinée-Bissau,105
Guyana,Guyana,107
Haiti,Haïti,108
Heard Island and McDonald Mcdonald Islands,Heard-Et-Îles Macdonald; Île,109
Holy See (Vatican City State),Saint-Siège (État de la Cité du Vatican),110
Honduras,Honduras,111
Hong Kong,Hong Kong,33364
Hungary,Hongrie,113
Iceland,Islande,114
India,Inde,115
Indonesia,Indonésie,116
Iran; Islamic Republic of,Iran; République Islamique d'',117
Iraq,Iraq,118
Ireland,Irlande,119
Isle of Man,Île de Man,120
Israel,Israël,121
Italy,Italie,122
Jamaica,Jamaïque,123
Japan,Japon,126
Jersey,Jersey,128
Jordan,Jordanie,130
Kazakhstan,Kazakhstan,132
Kenya,Kenya,133
Kiribati,Kiribati,135
Korea; Democratic People''s Republic of,Corée; République Populaire Démocratique de,67
Korea; Republic of,Corée; République de,202
Kuwait,Koweït,137
Kyrgyzstan,Kirghizistan,138
Lao People''s Democratic Republic,Lao; République Démocratique Populaire,139
Latvia,Lettonie,140
Lebanon,Liban,141
Lesotho,Lesotho,142
Liberia,Libéria,144
Libya,Libye,145
Liechtenstein,Liechtenstein,146
Lithuania,Lituanie,147
Luxembourg,Luxembourg,148
Macao,Macao,149
Macedonia; the Former Yugoslav Republic of,Macédoine; l''Ex-république Yougoslave de,241
Madagascar,Madagascar,150
Malawi,Malawi,152
Malaysia,Malaisie,153
Maldives,Maldives,154
Mali,Mali,155
Malta,Malte,156
Marshall Islands,Marshall; Îles,157
Martinique,Martinique,158
Mauritania,Mauritanie,159
Mauritius,Maurice,160
Mayotte,Mayotte,161
Mexico,Mexique,162
Micronesia; Federated States of,Micronésie; États Fédérés de,163
Moldova; Republic of,Moldova; République de,165
Monaco,Monaco,166
Mongolia,Mongolie,167
Montenegro,Monténégro,2647
Montserrat,Montserrat,168
Morocco,Maroc,169
Mozambique,Mozambique,170
Myanmar,Myanmar,171
Namibia,Namibie,172
Nauru,Nauru,173
Nepal,Népal,175
Netherlands,Pays-Bas,177
New Caledonia,Nouvelle-Calédonie,178
New Zealand,Nouvelle-Zélande,179
Nicaragua,Nicaragua,180
Niger,Niger,181
Nigeria,Nigéria,182
Niue,Niué,183
Norfolk Island,Norfolk; Île,184
Northern Mariana Islands,Mariannes du Nord; Îles,185
Norway,Norvège,186
Oman,Oman,187
Pakistan,Pakistan,188
Palau,Palaos,189
Palestine; State of,Palestine; État de,91 267
Panama,Panama,191
Papua New Guinea,Papouasie-Nouvelle-Guinée,192
Paraguay,Paraguay,194
Peru,Pérou,195
Philippines,Philippines,196
Pitcairn,Pitcairn,197
Poland,Pologne,198
Portugal,Portugal,199
Puerto Rico,Porto Rico,200
Qatar,Qatar,201
Romania,Roumanie,203
Russian Federation,Russie; Fédération de,204
Rwanda,Rwanda,205
Réunion,Réunion,206
Saint Barthélemy,Saint-Barthélemy,
Saint Helena; Ascension and Tristan da Cunha,Sainte-Hélène; Ascension et Tristan da Cunha,207
Saint Kitts and Nevis,Saint-Kitts-Et-Nevis,208
Saint Lucia,Sainte-Lucie,209
Saint Martin (French part),Saint-Martin(partie Française),
Saint Pierre and Miquelon,Saint-Pierre-Et-Miquelon,210
Saint Vincent and the Grenadines,Saint-Vincent-Et-Les Grenadines,211
Samoa,Samoa,212
San Marino,Saint-Marin,213
Sao Tome and Principe,Sao Tomé-Et-Principe,214
Saudi Arabia,Arabie Saoudite,215
Senegal,Sénégal,217
Serbia,Serbie,2648
Seychelles,Seychelles,220
Sierra Leone,Sierra Leone,221
Singapore,Singapour,222
Sint Maarten (Dutch part),Saint-Martin (Partie Néerlandaise),
Slovakia,Slovaquie,223
Slovenia,Slovénie,224
Solomon Islands,Salomon; Îles,225
Somalia,Somalie,226
South Africa,Afrique du Sud,227
South Georgia and the South Sandwich Islands,Géorgie du Sud-Et-Les Îles Sandwich du Sud,228
South Sudan,Soudan du Sud,
Spain,Espagne,229
Sri Lanka,Sri Lanka,231
Sudan,Soudan,40764
Suriname,Suriname,233
Svalbard and Jan Mayen,Svalbard et Île Jan Mayen,234
Swaziland,Swaziland,235
Sweden,Suède,236
Switzerland,Suisse,237
Syrian Arab Republic,Syrienne; République Arabe,238
Taiwan; Province of China,Taïwan; Province de Chine,925
Tajikistan,Tadjikistan,239
Tanzania; United Republic of,Tanzanie; République-Unie de,257
Thailand,Thaïlande,240
Timor-Leste,Timor-Leste,242
Togo,Togo,243
Tokelau,Tokelau,244
Tonga,Tonga,245
Trinidad and Tobago,Trinité-Et-Tobago,246
Tunisia,Tunisie,248
Turkey,Turquie,249
Turkmenistan,Turkménistan,250
Turks and Caicos Islands,Turks-Et-Caïcos; Îles,251
Tuvalu,Tuvalu,252
Uganda,Ouganda,253
Ukraine,Ukraine,254
United Arab Emirates,Émirats Arabes Unis,255
United Kingdom,Royaume-Uni,256
United States,États-Unis,259
United States Minor Outlying Islands,Îles Mineures Éloignées des États-Unis,
Uruguay,Uruguay,260
Uzbekistan,Ouzbékistan,261
Vanuatu,Vanuatu,262
Venezuela; Bolivarian Republic of,Venezuela; République Bolivarienne du,263
Viet Nam,Viet Nam,264
Virgin Islands; British,Îles Vierges Britanniques,39
Virgin Islands; U.S.,Îles Vierges des États-Unis,258
Wallis and Futuna,Wallis et Futuna,266
Western Sahara,Sahara Occidental,268
Yemen,Yémen,269
Zambia,Zambie,270
Zimbabwe,Zimbabwe,271
Åland Islands,Åland; Îles,1242
'