private
worldAreas
	" Private - This will be removed when people stops mixing data types "

	^ 'group type="001" contains="002 009 019 142 150" 
Comment World 
Comment Western Africa 
Comment Central America 
Comment Eastern Africa 
group type="142" contains="030 035 143 145 034 062" 
Comment Asia 
Comment  Central Asia 
Comment Western Asia 
Comment Northern Africa 
group type="150" contains="039 151 154 155 QU" 
Comment Europe 
Comment Eastern Europe 
Comment Northern Europe 
Comment Channel Islands 
Comment Western Europe 
Comment Middle Africa 
Comment  Commonwealth of Independent States 
Comment Southern Africa 
group type="019" contains="005 013 021 029 003 419" 
Comment Americas 
group type="002" contains="011 014 015 017 018" 
Comment Africa 
Comment Northern America 
Comment Caribbean 
group type="003" contains="013 021 029" 
Comment North America 
Comment Eastern Asia 
Comment South-Eastern Asia 
Comment Southern Europe 
group type="419" contains="005 013 029" 
Comment Latin America and the Caribbean 
Comment South America 
Comment Australia and New Zealand 
Comment Melanesia 
Comment Micronesia 
Comment Polynesia 
group type="062" contains="034 143" 
Comment South-Central Asia 
Comment Southern Asia 
group type="009" contains="053 054 057 061 QO" 
Comment Oceania 
Comment Outlying Oceania'