private
nonSpanishCaribbean
	" Answer a Collection with stable subdivisions "

	^ '660	Anguilla
028	Antigua and Barbuda
533	Aruba
044	Bahamas
052	Barbados
535	Bonaire, Saint Eustatius and Saba
092	British Virgin Islands
136	Cayman Islands
531	Curacao
212	Dominica
308	Grenada
312	Guadeloupe
332	Haiti
388	Jamaica
474	Martinique
500	Montserrat
652	Saint-Barthelemy
659	Saint Kitts and Nevis/St. Kitts and Nevis
662	Saint Lucia/St. Lucia
663	Saint Martin (French part)/St. Martin
670	Saint Vincent and the Grenadines/St. Vincent and the Grenadines
534	Sint Maarten (Dutch part)/St. Maarten
780	Trinidad and Tobago
796	Turks and Caicos Islands
850	United States Virgin Islands'