accessing-countries
northernEurope
	" Answer a Collection with stable subdivisions "

	^ self new initializeWith: '248	Åland Islands
830	Channel Islands
208	Denmark
233	Estonia
234	Faeroe Islands
246	Finland
831	Guernsey
352	Iceland
372	Ireland
833	Isle of Man
832	Jersey
428	Latvia
440	Lithuania
578	Norway
680	Sark
744	Svalbard and Jan Mayen Islands
752	Sweden
826	United Kingdom of Great Britain and Northern Ireland'