initialize-release
countryDemonymsListSpanish

	^ 'Argentina,Argentino/Argentina
Bolivia, Boliviano/Boliviana
Chile,Chileno/Chilena
Colombia,Colombiano/Colombiana
Costa Rica,Costarricence
Cuba,Cubano/Cubana
Ecuador,Ecuatoriano/Ecuatoriana
España,Español/Española
Guatemala,Guatemalteco/Guatemalteca
Haiti,Haitiano/Haitiana
Mexico,Mexicano/Mexicana
Nicaragua,Nicaraguense
Paraguay,Paraguayo/Paraguaya
Peru,Peruano/Peruana
República Dominicana,Dominicano/Dominicana
San Vicente y Las Granadinas,Sanvicentino/Sanvicentina
Santa Lucía,Santalucense
Santo Tomé y Príncipe,Santotomense
Uruguay,Uruguayo/Uruguaya
Venezuela,Venezolano/Venezolana
'