examples
exampleGoT1

	^ 'Known World' asTerritorialComposite
		addTerritory: ('Westeros' asTerritorialComposite
			addTerritory: 'Beyond the Wall' asTerritorialComposite;
			addTerritory: 'The North' asTerritorialComposite;
			addTerritory: 'Iron Islands' asTerritorialComposite;
			addTerritory: 'The Vale of Arryn' asTerritorialComposite;
			addTerritory: 'The Riverlands' asTerritorialComposite;
			addTerritory: 'The Westerlands' asTerritorialComposite;
			addTerritory: 'The Reach' asTerritorialComposite;
			addTerritory: 'The Stormlands' asTerritorialComposite;
			addTerritory: 'The Crownlands' asTerritorialComposite;
			addTerritory: 'Dorne' asTerritorialComposite;
			yourself);
		addTerritory: ('Essos' asTerritorialComposite
			addTerritory: 'Dothraki Sea' asTerritorialComposite;
			addTerritory: 'Free Cities' asTerritorialComposite;
			addTerritory: 'Ghiscar' asTerritorialComposite;
			addTerritory: 'Ifequevron' asTerritorialComposite;
			addTerritory: 'Jhogwin' asTerritorialComposite;
			addTerritory: 'Jogos Nhai' asTerritorialComposite;
			addTerritory: 'Lhazar' asTerritorialComposite;
			addTerritory: 'Mossovy' asTerritorialComposite;
			addTerritory: 'Red Waste' asTerritorialComposite;
			addTerritory: 'Sarnor' asTerritorialComposite;
			addTerritory: 'Shadow Lands' asTerritorialComposite;
			addTerritory: 'Slaver''s Bay' asTerritorialComposite;
			addTerritory: 'Valyria' asTerritorialComposite;
			addTerritory: 'Yi Ti' asTerritorialComposite;
			yourself);
		addTerritory: ('Sothoryos' asTerritorialComposite
			addTerritory: 'Ax Isle' asTerritorialComposite;
			addTerritory: 'Basilisk Isles' asTerritorialComposite;
			addTerritory: 'Basilisk Point' asTerritorialComposite;
			addTerritory: 'Isle of Tears' asTerritorialComposite;
			addTerritory: 'Isle of Toads' asTerritorialComposite;
			addTerritory: 'Naath' asTerritorialComposite;
			addTerritory: 'Wyvern Point' asTerritorialComposite;
			yourself);
		yourself.