accessing-countries
caribbean
	" Answer a Collection with stable subdivisions "

	^ self basicNew initializeWith: '660	Anguilla
028	Antigua and Barbuda
533	Aruba
044	Bahamas
052	Barbados
535	Bonaire, Saint Eustatius and Saba
092	British Virgin Islands
136	Cayman Islands
192	Cuba
531	Curacao
212	Dominica
214	Dominican Republic
308	Grenada
312	Guadeloupe
332	Haiti
388	Jamaica
474	Martinique
500	Montserrat
630	Puerto Rico
652	Saint-Barthelemy
659	Saint Kitts and Nevis
662	Saint Lucia
663	Saint Martin
670	Saint Vincent and the Grenadines
534	Saint Maarten
780	Trinidad and Tobago
796	Turks and Caicos Islands
850	United States Virgin Islands'