territorial-organizations
addC40

	^ self new
		preferredName: 'C40';
		denomination:  'C40 Cities Climate Leadership Group';
		bePolitical;
		beEconomical;
		url: 'http://www.c40.org';
		populateWith: 'Addis Ababa
Amman
Athens
Bangkok
Bengaluru
Berlin
Bogotá
Boston
Buenos Aires
Cairo
Caracas
Chicago
Delhi NCT
Dubai
Dhaka
Hanoi
Ho Chi Minh
City
Houston
Hong Kong
Istanbul
Jaipur
Jakarta
Johannesburg
Karachi
Lagos
Lima
London
Los
Angeles
Madrid
Melbourne
Mexico City
Milan
Moscow
Mumbai
New York
Paris
Philadelphia
Quezon City
Rio de Janeiro
Rome
Salvador
Sao Paulo
Seoul
Shenzhen
Sydney
Tokyo
Toronto
Warsaw
Washington DC
Wuhan and
Yokohoma';
		yourself
