territorial-organizations
addISO37120

	| co |
	co := self new.
	^ co
		preferredName: 'ISO 37120';
		denomination:  'ISO 37120 Sustainable Development of Communities: Indicators for City Services and Quality of Life';
		bePolitical;
		beEconomical;
		url: 'http://www.iso.org/iso/catalogue_detail?csnumber=62436';
		populateWith: 'London
Barcelona
Amsterdam
Rotterdam
Helsinki
Boston
Toronto
';
		yourself
