SystemOrganization addCategory: #Territorial!
SystemOrganization addCategory: #'Territorial-Core'!
SystemOrganization addCategory: #'Territorial-Geopolitics'!
SystemOrganization addCategory: #'Territorial-Geoprocessing'!
SystemOrganization addCategory: #'Territorial-Identifiers'!
SystemOrganization addCategory: #'Territorial-Maps'!
SystemOrganization addCategory: #'Territorial-Markers'!
SystemOrganization addCategory: #'Territorial-Organization'!
