accessing
countryDemonymsListEnglish

	^ 'Abkhazia,Abkhaz
Afghanistan,Afghan
Albania,Albanian
Algeria,Algerian
American Samoan,American Samoan
Andorra,Andorran
Angola,Angolan
Anguilla,Anguillan
Antigua and Barbuda,Antiguan/Barbudan
Argentina,Argentine
Armenia,Armenian
Aruba,Aruban
Australia,Australian
Austria,Austrian
Azerbaijan,Azerbaijani
Bahamas,Bahamian
Bahrain,Bahraini
Bangladesh,Bengali
Barbados,Barbadian
Belarus,Belarusian
Belgium,Belgian
Belize,Belizean
Benin,Beninese
Bermuda,Bermudian
Bhutan,Bhutanese
Bolivia,Bolivian
Bosnia and Herzegovina,Bosnian/Bosniak/Herzegovinian
Botswana,Motswana/Botswanan
Brazil,Brazilian
British Virgin Islands,British Virgin Island
Brunei,Bruneian
Bulgaria,Bulgarian
Burkina Faso,Burkinabè/Burkinabé
Burma,Burmese
Burundi,Burundian
Cambodia,Khmer
Cameroon,Cameroonian
Canada,Canadian
Cape Verde,Cape Verdean
Cayman Islands,Caymanian
Central African Republic,Central African
Chad,Chadian
Chile,Chilean
China,Chinese
Republic of China,Taiwan
Christmas Island,Christmas Island
Cocos (Keeling) Islands,Cocos Island
Colombia,Colombian
Comoros,Comorian
Republic of the Congo,Congolese
Cook Island,Cook Island
Costa Rica,Costa Rican
Côte d''Ivoire,Ivorian
Croatia,Croatian
Cuba,Cuban
Curaçao,Curaçaoan
Cyprus,Cypriot
Czech Republic,Czech
Denmark,Danish
Djibouti,Djiboutian
Dominica,Dominican
Dominican Republic,Dominican
East Timor,Timorese
Ecuador,Ecuadorian
Egypt,Egyptian
El Salvador,Salvadoran
England,English
Equatorial Guinea,Equatorial Guinean
Eritrea,Eritrean
Estonia,Estonian
Ethiopia,Ethiopian
Falkland Islands,Falkland Islanders
Faroe Islands,Faroese
Fiji,Fijian
Finland,Finnish
France,French
French Guiana,French Guianese
French Polynesia,French Polynesian
Gabon,Gabonese
Gambia,Gambian
Georgia,Georgian
Germany,German
Ghana,Ghanaian
Gibraltar,Gibraltar
Great Britain,British
Greece,Greek
Greenland,Greenlandic
Grenada,Grenadian
Guadeloupe,Guadeloupe
Guam,Guamanian
Guatemala,Guatemalan
Guinea,Guinean
Guinea-Bissau,Guinean
Guyana,Guyanese
Haiti,Haitian
Honduras,Honduran
Hong Kong,Hong Kong
Hungary,Hungarian/Magyay
Iceland,Icelandic
India,Indian
Indonesia,Indonesian
Iran,Iranian
Iraq,Iraqi
Ireland,Irish
Isle of Man,Manx
Israel,Israeli
Italy,Italian
Jamaica,Jamaican
Japan,Japanese
Jordan,Jordanian
Kazakhstan,Kazakh
Kenya,Kenyan
Kiribati,Kiribati
North Korea,North Korean
South Korea,South Korean
Kosovo,Kosovar
Kuwait,Kuwaiti
Kyrgyzstan,Kyrgyzstani
Laos,Lao
Latvia,Latvian
Lebanon,Lebanese
Lesotho,Basotho
Liberia,Liberian
Libya,Libyan
Liechtenstein,Liechtenstein
Lithuania,Lithuanian
Luxembourg,Luxembourg
Macau,Macanese
Macedonia,Macedonian
Madagascar,Malagasy
Malawi,Malawia
Malaysia,Malaysian
Maldives,Maldivian
Mali,Malian
Malta,Maltese
Marshall Islands,Marshallese
Martinique,Martiniquais
Mauritania,Mauritanian
Mauritius,Mauritian
Mayotte,Mahoran
Mexico,Mexican
Micronesia,Micronesian
Moldova,Moldovan
Monaco,Monégasque
Mongolia,Mongolian
Montenegro,Montenegrin
Montserrat,Montserratian
Morocco,Moroccan
Mozambique,Mozambican
Namibia,Namibian
Nauru,Nauruan
Nepal,Nepali
Netherlands,Dutch
New Caledonia,New Caledonian
New Zealand,New Zealanders
Nicaragua,Nicaraguan
Niue,Niuean
Niger,Nigerien
Nigeria,Nigerian
Norway,Norwegian
Northern Ireland,Northern Irish
Northern Marianas,Northern Marianan
Oman,Omani
Pakistan,Pakistani
Palestinian territories,Palestinian
Palau,Palauan
Panama,Panamanian
Papua New Guinea,Papua New Guinean
Paraguay,Paraguayan
Peru,Peruvian
Philippines,Philippine
Pitcairn Island,Pitcairn Island
Poland,Polish
Portugal,Portuguese
Puerto Rico,Puerto Rican
Qatar,Qatari
Réunion,Réunionese
Romania,Romanian
Russia,Russian
Rwanda,Rwandan
Saint Helena,Saint Helenian
Saint Kitts and Nevis,Kittitian
Saint Lucia,Saint Lucian
Saint-Pierre and Miquelon,Saint-Pierrais
Saint Vincent and the Grenadines,Saint Vincentian
Samoa,Samoan
San Marino,Sammarinese
São Tomé and Príncipe,São Toméan
Saudi Arabia,Saudi
Scotland,Scots/Scottish/Scotch
Senegal,Senegalese
Serbia,Serbian
Seychelles,Seychellois
Sierra Leone,Sierra Leonean
Singapore,Singapore
Slovakia,Slovak
Slovenia,Slovene
Solomon Islands,Solomon Island
Somalia,Somali
South Africa,South African
South Ossetia,South Ossetian
Spain,Spanish
Sri Lanka,Sri Lankan
Sudan,Sudanese
Surinam,Surinamese
Swaziland,Swazi
Sweden,Swedish
Switzerland,Swiss
Syria,Syrian
Taiwan,Taiwanese
Tajikistan,Tajikistani
Tanzania,Tanzanian
Thailand,Thai
Togo,Togolese
Tonga,Tongan
Trinidad and Tobago,Trinidadian
Tunisia,Tunisian
Turkey,Turk
Turkmenistan,Turkmen
Turks and Caicos Islands,None
Tuvalu,Tuvaluan
Uganda,Ugandan
Ukraine,Ukrainian
United Arab Emirates,Emirati
United Kingdom,British
United States of America,American
Uruguay,Uruguayan
Uzbekistan,Uzbekistani
Vanuatu,Ni-Vanuatu
Venezuela,Venezuelan
Vietnam,Vietnamese
Virgin Islands,Virgin Island
Wales,Welsh
Wallis and Futuna,Wallisian
Western Sahara,Sahraw
Yemen,Yemeni
Zambia,Zambian
Zimbabwe,Zimbabwean'