initialization
territorialQualifiers
	" Answer a <Collection> of all possible territorial organization qualifiers "

	^  { 'Political' -> 'Groups areas based on political units such as independent states and international groupings' .
	'Global' -> 'Organizations covering the whole world' .
	'Economical' -> 'Region that has produced goods and services.' .
	'Fictional' -> 'Territorial regions invented by man' .
	'Historical' -> 'Former geographic areas whose names are obsolete or have fallen out of use' .
	'Social' -> 'Organizations that adopt social missions and work to provide social benefits' .
	'Military' -> 'Organizations whose function is the use of armed force, or the threat of such use, against enemies' .
	'Regional' -> 'Groups organizations around natural resources' }