accessing-countries
new

	^ self basicNew initializeWith: 'Afghanistan,Afghanistan,AF
Albania,Albanie,AB
Algeria,Algérie,AL
Angola,Angola,AN
Antarctica,Antarctique,AA
Antigua and Barbuda,Antigua-Et-Barbuda,AT
Argentina,Argentine,AG
Armenia,Arménie,AY
Aruba,Aruba,NU
Australia,Australie,AU
Austria,Autriche,OS
Azerbaijan,Azerbaïdjan,AJ
Bahamas,Bahamas,BA
Bahrain,Bahreïn,BN
Bangladesh,Bangladesh,BW
Barbados,Barbade,BR
Belarus,Bélarus,BY
Belgium,Belgique,BX
Belize,Belize,BH
Benin,Bénin,BJ
Bermuda,Bermudes,BE
Bolivia; Plurinational State of,Bolivie; l''État Plurinational de,BO
Bonaire; Sint Eustatius and Saba,Bonaire; Saint-Eustache et Saba,NU
Bosnia and Herzegovina,Bosnie-Herzégovine,BG
Botswana,Botswana,BC
Bouvet Island,Bouvet; Île,BV
Brazil,Brésil,BZ
Brunei Darussalam,Brunei Darussalam,BD
Bulgaria,Bulgarie,BU
Burkina Faso,Burkina Faso,HV
Burundi,Burundi,BI
Cambodia,Cambodge,KP
Cameroon,Cameroun,CM
Canada,Canada,CN
Cape Verde,Cap-Vert,CV
Cayman Islands,Caïmans; Îles,GC
Central African Republic,Centrafricaine; République,CE
Chad,Tchad,CD
Chile,Chili,CH
China,Chine,CI
Christmas Island,Christmas; Île,KI
Cocos (Keeling) Islands,Cocos (Keeling); Îles,KK
Colombia,Colombie,CO
Comoros,Comores,IC
Congo,Congo,CG
Congo; the Democratic Republic of the,Congo; la République Démocratique du,ZR
Cook Islands,Cook; Îles,KU
Costa Rica,Costa Rica,CS
Croatia,Croatie,RH
Cuba,Cuba,CU
Cyprus,Chypre,CY
Czech Republic,Tchèque; République,CZ
Côte d''Ivoire,Côte d''Ivoire,IV
Denmark,Danemark,DN
Djibouti,Djibouti,DJ
Dominica,Dominique,DO
Dominican Republic,Dominicaine; République,DR
Ecuador,Équateur,EQ
Egypt,Égypte,EG
El Salvador,El Salvador,ES
Equatorial Guinea,Guinée Équatoriale,GQ
Estonia,Estonie,EO
Ethiopia,Éthiopie,ET
Falkland Islands (Malvinas),Falkland; Îles (Malvinas),FK
Faroe Islands,Féroé; Îles,FA
Fiji,Fidji,FJ
Finland,Finlande,FI
France,France,FR
French Guiana,Guyane Française,FG
French Polynesia,Polynésie Française,PF
Gabon,Gabon,GO
Gambia,Gambie,GB
Georgia,Géorgie,GG
Germany,Allemagne,DL
Ghana,Ghana,GH
Gibraltar,Gibraltar,GI
Greece,Grèce,GR
Greenland,Groenland,GL
Grenada,Grenade,GD
Guadeloupe,Guadeloupe,MF
Guam,Guam,GM
Guatemala,Guatemala,GU
Guinea,Guinée,GN
Guinea-Bissau,Guinée-Bissau,GW
Guyana,Guyana,GY
Haiti,Haïti,HA
Honduras,Honduras,HO
Hong Kong,Hong Kong,HK
Hungary,Hongrie,HU
Iceland,Islande,IL
India,Inde,IN
Indonesia,Indonésie,ID
Iran; Islamic Republic of,Iran; République Islamique d'',IR
Iraq,Iraq,IQ
Ireland,Irlande,IE
Israel,Israël,IS
Italy,Italie,IY
Jamaica,Jamaïque,JM
Japan,Japon,JP
Jordan,Jordanie,JD
Kazakhstan,Kazakhstan,KZ
Kenya,Kenya,KN
Kiribati,Kiribati,KB
Korea; Democratic People''s Republic of,Corée; République Populaire Démocratique de,KR
Korea; Republic of,Corée; République de,KO
Kuwait,Koweït,KW
Kyrgyzstan,Kirghizistan,KG
Lao People''s Democratic Republic,Lao; République Démocratique Populaire,LA
Latvia,Lettonie,LV
Lebanon,Liban,LB
Lesotho,Lesotho,LS
Liberia,Libéria,LI
Libya,Libye,LY
Lithuania,Lituanie,LT
Luxembourg,Luxembourg,BX
Macao,Macao,MU
Macedonia; the Former Yugoslav Republic of,Macédoine; l''Ex-république Yougoslave de,MJ
Madagascar,Madagascar,MG
Malawi,Malawi,MW
Malaysia,Malaisie,MS
Maldives,Maldives,MV
Mali,Mali,MI
Malta,Malte,ML
Marshall Islands,Marshall; Îles,MH
Martinique,Martinique,MR
Mauritania,Mauritanie,MT
Mauritius,Maurice,MA
Mexico,Mexique,MX
Moldova; Republic of,Moldova; République de,RM
Mongolia,Mongolie,MO
Morocco,Maroc,MC
Mozambique,Mozambique,MZ
Myanmar,Myanmar,BM
Namibia,Namibie,NM
Nauru,Nauru,NW
Nepal,Népal,NP
Netherlands,Pays-Bas,NL
New Caledonia,Nouvelle-Calédonie,NC
New Zealand,Nouvelle-Zélande,NZ
Nicaragua,Nicaragua,NK
Niger,Niger,NR
Nigeria,Nigéria,NI
Norfolk Island,Norfolk; Île,NF
Northern Mariana Islands,Mariannes du Nord; Îles,MY
Norway,Norvège,NO
Oman,Oman,OM
Pakistan,Pakistan,PK
Panama,Panama,PM
Papua New Guinea,Papouasie-Nouvelle-Guinée,NG
Paraguay,Paraguay,PY
Peru,Pérou,PR
Philippines,Philippines,PH
Pitcairn,Pitcairn,PT
Poland,Pologne,PL
Portugal,Portugal,PO
Puerto Rico,Porto Rico,PU
Qatar,Qatar,QT
Romania,Roumanie,RO
Russian Federation,Russie; Fédération de,RS
Rwanda,Rwanda,RW
Réunion,Réunion,RE
Saint Helena; Ascension and Tristan da Cunha,Sainte-Hélène; Ascension et Tristan da Cunha,HE
Saint Kitts and Nevis,Saint-Kitts-Et-Nevis,AT
Saint Lucia,Sainte-Lucie,LC
Saint Pierre and Miquelon,Saint-Pierre-Et-Miquelon,FP
Saint Vincent and the Grenadines,Saint-Vincent-Et-Les Grenadines,VG
Samoa,Samoa,ZM
Sao Tome and Principe,Sao Tomé-Et-Principe,TP
Saudi Arabia,Arabie Saoudite,SD
Senegal,Sénégal,SG
Serbia,Serbie,YG
Seychelles,Seychelles,SC
Sierra Leone,Sierra Leone,SL
Singapore,Singapour,SR
Slovakia,Slovaquie,SQ
Slovenia,Slovénie,LJ
Solomon Islands,Salomon; Îles,SO
Somalia,Somalie,SI
South Africa,Afrique du Sud,ZA
Spain,Espagne,SP
Sri Lanka,Sri Lanka,SB
Sudan,Soudan,SU
Suriname,Suriname,SM
Svalbard and Jan Mayen,Svalbard et Île Jan Mayen,SZ
Swaziland,Swaziland,SV
Sweden,Suède,SN
Switzerland,Suisse,SW
Syrian Arab Republic,Syrienne; République Arabe,SY
Tajikistan,Tadjikistan,TA
Tanzania; United Republic of,Tanzanie; République-Unie de,TN
Thailand,Thaïlande,TH
Timor-Leste,Timor-Leste,TM
Togo,Togo,TG
Tokelau,Tokelau,TK
Tonga,Tonga,TO
Trinidad and Tobago,Trinité-Et-Tobago,TD
Tunisia,Tunisie,TS
Turkey,Turquie,TU
Turkmenistan,Turkménistan,TR
Turks and Caicos Islands,Turks-Et-Caïcos; Îles,TI
Tuvalu,Tuvalu,TV
Uganda,Ouganda,UG
Ukraine,Ukraine,UR
United Arab Emirates,Émirats Arabes Unis,ER
United Kingdom,Royaume-Uni,UK
United States,États-Unis,US
Uruguay,Uruguay,UY
Uzbekistan,Ouzbékistan,UZ
Vanuatu,Vanuatu,NV
Venezuela; Bolivarian Republic of,Venezuela; République Bolivarienne du,VN
Viet Nam,Viet Nam,VS
Virgin Islands; British,Îles Vierges Britanniques,VI
Virgin Islands; U.S.,Îles Vierges des États-Unis,VI
Wallis and Futuna,Wallis et Futuna,FW
Yemen,Yémen,YE
Zambia,Zambie,ZB
Zimbabwe,Zimbabwe,ZW
'