territorial-organizations
addCARICOM

	^ TCountryOrganization new
		preferredName: 'CARICOM';
		addName:  'Caribbean Community and Common Market';
		qualifiers: #('Regional' 'Political' 'Economical');
		populateWith: 'Antigua and Barbuda
Bahamas
Barbados
Belize
Dominica
Grenada
Guyana
Haiti
Jamaica
Saint Kitts and Nevis
Saint Lucia
Saint Vincent and the Grenadines
Suriname
Trinidad and Tobago';
		yourself