territorial-organizations
addCEEAC

	^ TCountryOrganization new
		denomination: 'CEEAC';
		formedYear: 1964;
		url: 'http://www.ceeac-eccas.org/';
		description:  'Economic Community of Central African States';
		qualifiers: #('Economical');
		territoryList: 'Angola
Burundi
Cameroon
Central African Republic
Chad
Congo
Democratic Republic of the Congo
Equatorial Guinea
Gabon
Rwanda
Sao Tome and Principe';
		yourself