territorial-organizations
addCARICOM

	^ TCountryOrganization new
		preferredName: 'CARICOM';
		denomination:  'Caribbean Community and Common Market';
		beRegional;
		bePolitical;
		beEconomical;
		populateWith: 'Antigua and Barbuda
Bahamas
Barbados
Belize
Dominica
Grenada
Guyana
Haiti
Jamaica
Saint Kitts and Nevis
Saint Lucia
Saint Vincent and the Grenadines
Suriname
Trinidad and Tobago';
		yourself