territorial-organizations
addCARIFORUM

	^ TCountryOrganization new
		denomination: 'CARIFORUM';
		formedYear: 1992;
		description:  'Caribbean Forum';
		qualifiers: #('Economical');
		territoryList: 'Antigua and Barbuda
Bahamas
Barbados
Belize
Dominica
Dominican Republic
Grenada
Guyana
Haiti
Jamaica
Saint Kitts and Nevis
Saint Lucia
Saint Vincent and the Grenadines
Suriname
Trinidad and Tobago';
		yourself