territorial-organizations
addEU

	^ TCountryOrganization new
		denomination: 'EU';
		formedYear: 1957;
		url: 'http://europa.eu/';
		description:  'European Union';
		qualifiers: #('Regional' 'Political' 'Economical');
		territoryList: 'Austria
Belgium
Bulgaria
Cyprus
Czech Republic
Denmark
Estonia
Finland
France
Germany
Greece
Hungary
Ireland
Italy
Latvia
Lithuania
Luxembourg
Malta
Netherlands
Poland
Portugal
Romania
Slovakia
Slovenia
Spain
Sweden
United Kingdom';
		yourself