territorial-organizations
addEU

	^ TCountryOrganization new
		preferredName: 'EU';
		formedYear: 1957;
		url: 'http://europa.eu/';
		denomination:  'European Union';
		beRegional;
		bePolitical;
		beEconomical;
		populateWith: 'Austria
Belgium
Bulgaria
Cyprus
Czech Republic
Denmark
Estonia
Finland
France
Germany
Greece
Hungary
Ireland
Italy
Latvia
Lithuania
Luxembourg
Malta
Netherlands
Poland
Portugal
Romania
Slovakia
Slovenia
Spain
Sweden
United Kingdom';
		yourself