territorial-organizations
addFIFA

	^ TCountryOrganization new
		preferredName: 'FIFA';
		formedYear: 1904;
		url: 'http://www.fifa.com/';
		addName:  'Fédération Internationale de Football Association';
		qualifiers: #('Global' 'Economical');
		territoryList: 'Afghanistan,Afghanistan,AFG
Albania,Albanie,ALB
Algeria,Algérie,ALG
American Samoa,Samoa Américaines,ASA
Andorra,Andorre,AND
Angola,Angola,ANG
Anguilla,Anguilla,AIA
Antarctica,Antarctique,ROS
Antigua and Barbuda,Antigua-Et-Barbuda,ATG
Argentina,Argentine,ARG
Armenia,Arménie,ARM
Aruba,Aruba,ARU
Australia,Australie,AUS
Austria,Autriche,AUT
Azerbaijan,Azerbaïdjan,AZE
Bahamas,Bahamas,BAH
Bahrain,Bahreïn,BHR
Bangladesh,Bangladesh,BAN
Barbados,Barbade,BRB
Belarus,Bélarus,BLR
Belgium,Belgique,BEL
Belize,Belize,BLZ
Benin,Bénin,BEN
Bermuda,Bermudes,BER
Bhutan,Bhoutan,BHU
Bolivia; Plurinational State of,Bolivie; l''État Plurinational de,BOL
Bonaire; Sint Eustatius and Saba,Bonaire; Saint-Eustache et Saba,ANT
Bosnia and Herzegovina,Bosnie-Herzégovine,BIH
Botswana,Botswana,BOT
Brazil,Brésil,BRA
Brunei Darussalam,Brunei Darussalam,BRU
Bulgaria,Bulgarie,BUL
Burkina Faso,Burkina Faso,BFA
Burundi,Burundi,BDI
Cambodia,Cambodge,CAM
Cameroon,Cameroun,CMR
Canada,Canada,CAN
Cape Verde,Cap-Vert,CPV
Cayman Islands,Caïmans;Îles,CAY
Central African Republic,Centrafricaine; République,CTA
Chad,Tchad,CHA
Chile,Chili,CHI
China,Chine,CHN
Christmas Island,Christmas;Île,CXR
Cocos (Keeling) Islands,Cocos (Keeling);Îles,CCK
Colombia,Colombie,COL
Comoros,Comores,COM
Congo,Congo,CGO
Congo; the Democratic Republic of the,Congo; la République Démocratique du,COD
Cook Islands,Cook;Îles,COK
Costa Rica,Costa Rica,CRC
Croatia,Croatie,CRO
Cuba,Cuba,CUB
Cyprus,Chypre,CYP
Czech Republic,Tchèque; République,CZE
Côte d''Ivoire,Côte d''Ivoire,CIV
Denmark,Danemark,DEN
Djibouti,Djibouti,DJI
Dominica,Dominique,DMA
Dominican Republic,Dominicaine; République,DOM
Ecuador,Équateur,ECU
Egypt,Égypte,EGY
El Salvador,El Salvador,SLV
Equatorial Guinea,Guinée Équatoriale,EQG
Eritrea,Érythrée,ERI
Estonia,Estonie,EST
Ethiopia,Éthiopie,ETH
Falkland Islands (Malvinas),Falkland;Îles (Malvinas),FLK
Faroe Islands,Féroé;Îles,FRO
Fiji,Fidji,FIJ
Finland,Finlande,FIN
France,France,FRA
French Guiana,Guyane Française,GUF
French Polynesia,Polynésie Française,TAH
Gabon,Gabon,GAB
Gambia,Gambie,GAM
Georgia,Géorgie,GEO
Germany,Allemagne,GER
Ghana,Ghana,GHA
Gibraltar,Gibraltar,GBZ
Greece,Grèce,GRE
Greenland,Groenland,GRL
Grenada,Grenade,GRN
Guadeloupe,Guadeloupe,GLP
Guam,Guam,GUM
Guatemala,Guatemala,GUA
Guernsey,Guernesey,GBG
Guinea,Guinée,GUI
Guinea-Bissau,Guinée-Bissau,GNB
Guyana,Guyana,GUY
Haiti,Haïti,HAI
Holy See (Vatican City State),Saint-Siège (État de la Cité du Vatican),VAT
Honduras,Honduras,HON
Hong Kong,Hong Kong,HKG
Hungary,Hongrie,HUN
Iceland,Islande,ISL
India,Inde,IND
Indonesia,Indonésie,IDN
Iran; Islamic Republic of,Iran; République Islamique d'',IRN
Iraq,Iraq,IRQ
Ireland,Irlande,IRL
Isle of Man,Île de Man,GBM
Israel,Israël,ISR
Italy,Italie,ITA
Jamaica,Jamaïque,JAM
Japan,Japon,JPN
Jersey,Jersey,GBJ
Jordan,Jordanie,JOR
Kazakhstan,Kazakhstan,KAZ
Kenya,Kenya,KEN
Kiribati,Kiribati,KIR
Korea; Democratic People''s Republic of,Corée; République Populaire Démocratique de,PRK
Korea; Republic of,Corée; République de,KOR
Kuwait,Koweït,KUW
Kyrgyzstan,Kirghizistan,KGZ
Lao People''s Democratic Republic,Lao; République Démocratique Populaire,LAO
Latvia,Lettonie,LVA
Lebanon,Liban,LIB
Lesotho,Lesotho,LES
Liberia,Libéria,LBR
Libya,Libye,LBY
Liechtenstein,Liechtenstein,LIE
Lithuania,Lituanie,LTU
Luxembourg,Luxembourg,LUX
Macao,Macao,MAC
Macedonia; the Former Yugoslav Republic of,Macédoine; l''Ex-république Yougoslave de,MKD
Madagascar,Madagascar,MAD
Malawi,Malawi,MWI
Malaysia,Malaisie,MAS
Maldives,Maldives,MDV
Mali,Mali,MLI
Malta,Malte,MLT
Marshall Islands,Marshall;Îles,MHL
Martinique,Martinique,MTQ
Mauritania,Mauritanie,MTN
Mauritius,Maurice,MRI
Mayotte,Mayotte,MYT
Mexico,Mexique,MEX
Micronesia; Federated States of,Micronésie; États Fédérés de,FSM
Moldova; Republic of,Moldova; République de,MDA
Monaco,Monaco,MON
Mongolia,Mongolie,MNG
Montenegro,Monténégro,MNE
Montserrat,Montserrat,MSR
Morocco,Maroc,MAR
Mozambique,Mozambique,MOZ
Myanmar,Myanmar,MYA
Namibia,Namibie,NAM
Nauru,Nauru,NRU
Nepal,Népal,NEP
Netherlands,Pays-Bas,NED
New Caledonia,Nouvelle-Calédonie,NCL
New Zealand,Nouvelle-Zélande,NZL
Nicaragua,Nicaragua,NCA
Niger,Niger,NIG
Nigeria,Nigéria,NGA
Niue,Niué,NIU
Norfolk Island,Norfolk;Île,NFK
Northern Mariana Islands,Mariannes du Nord;Îles,NMI
Norway,Norvège,NOR
Oman,Oman,OMA
Pakistan,Pakistan,PAK
Palau,Palaos,PLW
Palestine; State of,Palestine; État de,PLE
Panama,Panama,PAN
Papua New Guinea,Papouasie-Nouvelle-Guinée,PNG
Paraguay,Paraguay,PAR
Peru,Pérou,PER
Philippines,Philippines,PHI
Pitcairn,Pitcairn,PCN
Poland,Pologne,POL
Portugal,Portugal,POR
Puerto Rico,Porto Rico,PUR
Qatar,Qatar,QAT
Romania,Roumanie,ROU
Russian Federation,Russie; Fédération de,RUS
Rwanda,Rwanda,RWA
Réunion,Réunion,REU
Saint Helena; Ascension and Tristan da Cunha,Sainte-Hélène; Ascension et Tristan da Cunha,SHN
Saint Kitts and Nevis,Saint-Kitts-Et-Nevis,SKN
Saint Lucia,Sainte-Lucie,LCA
Saint Pierre and Miquelon,Saint-Pierre-Et-Miquelon,SPM
Saint Vincent and the Grenadines,Saint-Vincent-Et-Les Grenadines,VIN
Samoa,Samoa,SAM
San Marino,Saint-Marin,SMR
Sao Tome and Principe,Sao Tomé-Et-Principe,STP
Saudi Arabia,Arabie Saoudite,KSA
Senegal,Sénégal,SEN
Serbia,Serbie,SRB
Seychelles,Seychelles,SEY
Sierra Leone,Sierra Leone,SLE
Singapore,Singapour,SIN
Slovakia,Slovaquie,SVK
Slovenia,Slovénie,SVN
Solomon Islands,Salomon;Îles,SOL
Somalia,Somalie,SOM
South Africa,Afrique du Sud,RSA
Spain,Espagne,ESP
Sri Lanka,Sri Lanka,SRI
Sudan,Soudan,SUD
Suriname,Suriname,SUR
Swaziland,Swaziland,SWZ
Sweden,Suède,SWE
Switzerland,Suisse,SUI
Syrian Arab Republic,Syrienne; République Arabe,SYR
Taiwan; Province of China,Taïwan; Province de Chine,TPE
Tajikistan,Tadjikistan,TJK
Tanzania; United Republic of,Tanzanie; République-Unie de,TAN
Thailand,Thaïlande,THA
Timor-Leste,Timor-Leste,TLS
Togo,Togo,TOG
Tokelau,Tokelau,TKL
Tonga,Tonga,TGA
Trinidad and Tobago,Trinité-Et-Tobago,TRI
Tunisia,Tunisie,TUN
Turkey,Turquie,TUR
Turkmenistan,Turkménistan,TKM
Turks and Caicos Islands,Turks-Et-Caïcos;Îles,TCA
Tuvalu,Tuvalu,TUV
Uganda,Ouganda,UGA
Ukraine,Ukraine,UKR
United Arab Emirates,Émirats Arabes Unis,UAE
United Kingdom,Royaume-Uni,ENG;NIR;SCO;WAL
United States,États-Unis,USA
Uruguay,Uruguay,URU
Uzbekistan,Ouzbékistan,UZB
Vanuatu,Vanuatu,VAN
Venezuela; Bolivarian Republic of,Venezuela; République Bolivarienne du,VEN
Viet Nam,Viet Nam,VIE
Virgin Islands; British,Îles Vierges Britanniques,VGB
Virgin Islands; U.S.,Îles Vierges des États-Unis,VIR
Wallis and Futuna,Wallis et Futuna,WLF
Western Sahara,Sahara Occidental,SAH
Yemen,Yémen,YEM
Zambia,Zambie,ZAM
Zimbabwe,Zimbabwe,ZIM
Åland Islands,Åland;Îles,ALD';
		fieldsBlock: [ : field | | country |
			country := ((TerritorialCountry newNamed: field first)
				addTerritoryName: #englishName -> field first;
				addTerritoryName: #frenchName -> field second;				
				yourself).
			(field second includes: $;)
				ifFalse: [ country addIdentifier: field second ]
				ifTrue: [ (field second findTokens: $;) do: [: id | country addIdentifier: id ] ].
			self countries add: country ];
		yourself