territorial-organizations
addNATO

	^ TCountryOrganization new
		denomination: 'NATO';
		formedYear: 1949;
		url: 'http://www.nato.int';
		description: 'North Atlantic Treaty Organization';
		qualifiers: #('Military');
		territoryList: 'Albania
Belgium
Bulgaria
Canada
Croatia
Czech Repblic
Denmark
Estonia
France
Germany
Greece
Hungary
Iceland
Italy
Latvia
Lithuania
Luxembourg
Netherlands
Norway
Poland
Portugal
Romania
Slovakia
Slovenia
Spain
Turkey
United Kingdom
United States';
		yourself