territorial-organizations
addNonSpanishCaribbean

	^ TCountryOrganization new
		addName: 'Non-Spanish West Indies';
		addName:  'Caribe No-Español';
		preferredName: 'Non Spanish Caribbean';
		formedYear: 1492 dissolvedYear: 1898;
		denomination:  'Caribe No Español';
		qualifiers: #('Historical');
		populateWith: 'Anguilla
Antigua and Barbuda
Aruba
Bahamas
Barbados
Bonaire, Saint Eustatius and Saba
British Virgin Islands
Cayman Islands
Curacao
Dominica
Grenada
Guadeloupe
Haiti
Jamaica
Martinique
Montserrat
Saint-Barthelemy
Saint Kitts and Nevis
Saint Lucia
Saint Martin (French part)
Saint Vincent and the Grenadines
Sint Maarten (Dutch part)
Trinidad and Tobago
Turks and Caicos Islands
United States Virgin Islands';
		yourself